version: 2
jobs:
  test:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:openjdk-11-lein-2.9.1

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      - run: lein test :all

      - store_artifacts:
          path: ./.lein-failures
          prefix: test-results
          when: on_fail

workflows:
  version: 2
  prs:
    jobs:
      - test:
          filters:
            branches:
              ignore: master