name: Clojure CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
 
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: lein deps
      uses: docker://circleci/clojure:openjdk-11-lein-2.9.1
    - name: Run tests
      run: lein test
      uses: docker://circleci/clojure:openjdk-11-lein-2.9.1
